core/urls.py
from django.urls import path, include
from Empresa.core import views 
urlpatterns = [ 
    path(r'', views.home, name='home'), 
    path(r'Empresas/', views.contact, name='contact'), 
    path('registrar/', views.signup, name='signup'),
    path('', include('django.contrib.auth.urls')),
    ]

registration/urls.py
from django.contrib.auth.views import LoginView
from django.urls import include, path


app_name = 'registration'
urlpatterns = [

    path('', include('django.contrib.auth.urls')),

]

urls.py
from django.contrib import admin 
from django.urls import include, path 

app_name='Empresa' 
urlpatterns = [ 
path(r'', include('Empresa.core.urls') ), 
path(r'', include('Empresa.registration.urls', namespace='registration') ), 
path(r'vagas/', include('Empresa.vacancies.urls', namespace='vacancies') ),
path('admin/', admin.site.urls), ]

vacancies/urls.py
from django.urls import path 
from Empresa.vacancies import views 

app_name= 'index'
urlpatterns = [ 
    path(r'', views.index, name='index'),
    path(r'^(?P<slug>[\w_-]+)/$', views.details, name='details'), 
    
    
    ]

core/models.py
from django.db import models

vacancies/models.py
from django.db import models
from django.conf import settings


class VacancieManager(models.Manager):

    def search(self, query):
        return self.get_queryset().filter(
            models.Q(title__icontains=query) | \
            models.Q(name__icontains=query)
        )

class Vacancie(models.Model):
    
    name = models.CharField('Nome da Vaga', max_length=100)
    slug = models.SlugField('Atalho', max_length=100)
    salary = models.IntegerField('Faixa Salarial')
    educational = models.CharField('Escolaridade', max_length=100)
   
   
    start_date = models.DateField(
        'Data de Início', null=True, blank=True
    )
    
    created_at = models.DateTimeField(
        'Criado em', auto_now_add=True
    )
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    objects = VacancieManager()

    def __str__(self):
        return self.name
    
    
    def get_absolute_url(self):
        return ('vacancies:details', (), {'slug': self.slug})

    class Meta:
        verbose_name = "Vaga"
        verbose_name_plural = "Vagas"
        ordering = ['name']

# class Enrollment(models.Model):

#     STATUS_CHOICES = (
#         (0, 'Pendente'),
#         (1, 'Aprovado'),
#         (2, 'Cancelado'),
#     )

#     user = models.ForeignKey(
#         #settings.AUTH_USER_MODEL, verbose_name='Usuário',
#         #related_name='enrollments'
#     )
#     #vacancie = models.ForeignKey(
#         #Vacancie, verbose_name='Vaga', related_name='enrollments'
#     )
#     status = models.IntegerField(
#         'Situação', choices=STATUS_CHOICES, default=1, blank=True
#     )

#     created_at = models.DateTimeField('Criado em', auto_now_add=True)
#     updated_at = models.DateTimeField('Atualizado em', auto_now=True)

#     def active(self):
#         self.status = 1
#         self.save()

class Meta:
        verbose_name = 'Inscrição'
        verbose_name_plural = 'Inscrições'
        unique_together = (('user', 'Vacancie'),)

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    email = forms.EmailField(label='E-mail')

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Já existe usuário com este E-mail')
        return email

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.salary = self.cleaned_data['Pretensão Salarial']
        user.education = self.cleaned_data['[Ultima Escolaridade]']
        user.exp = self.cleaned_data['Experiência']
        if commit:
            user.save()
        return user

core/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .forms import RegisterForm

app_name='core'

def home(request):
    count = User.objects.count()
    return render(request, 'home.html', {
        'count': count
    })

def contact(request):
    return render(request, 'contact.html')

def vacancies(request):
    return render(request, 'index.html')

def signup(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
          form.save()
        return redirect('home')
    else:
        form = RegisterForm()
    return render(request, 'signup.html', {
        'form': form
    })

vacancies/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User


from .models import Vacancie



def index(request):
    vacancies = Vacancie.objects.all()
    template_name = 'vacancies/index.html'
    context = {
        'vacancies': vacancies
    }
    return render(request, template_name, context)

def details(request, slug):
    vacancie = get_object_or_404(Vacancie, slug=slug)
    context = {
        'vacancie': vacancie
    }
    template_name = 'vacancie/details.html'
    return render(request, template_name, context)

core/templates/base.html
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<title>Meu Site</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
      <div class="container">
        <a class="navbar-brand" >Meu Site</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home' %}">Home</a>
            </li>
            <a class="nav-link" href="{% url 'vacancies:index' %}">Vagas</a>
            {% if user.is_authenticated %}
              
            {% endif %}
          </ul>
          {% if user.is_authenticated %}
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{user.username}}
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
               
                <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                </div>
            </li>
          </ul>
          {% else %}
          <form class="form-inline my-2 my-lg-0">
            <li><a href="{% url 'registration:login' %}"class="btn btn-outline-secondary">Logar</a></li>
            <li><a href="{% url 'signup' %}" class="btn btn-primary">Registrar</a></li>
          </form>
          {% endif %}
    </div>
</nav>
    <div class="container">
        {% block content %}
        {%endblock%}
</div>
</div>
</div>


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

core/templates/candidate.html
{% extends "base.html" %}

{% block content %}
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            <h1>Consulte todas as Vagas</h1>
            <p>Você pode procurar diversas vagas de sua preferência: </p>
            <h4>Vagas</h4>
            <ul>
                
            </ul>
        </div>
    </div>
{% endblock %}

core/templates/contact.html
{% extends "base.html" %}




{% block content %}
  <div class="row justify-content-center">
    <div class="col-6">
      <div class="card">
        <div class="card-body">
          <h2>Login</h2>
          <form method="post" novalidate>
            {% csrf_token %}
            
            <button type="submit" class="btn btn-primary">Log in</button>
            <a href="" class="btn btn-link">Forgot your password?</a>
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

core/templates/home.html
{% extends "base.html" %}

{% block content %}
    <div class="splash">
        <div class="pure-g-r">
            <div class="pure-u-1">
                <div class="l-box splash-text">
                    <h1 class="splash-head">
                       Um Site que vai achar a Vaga ideal Para Você!
                    </h1>
                    <br>
                    <br>
                    <br>
                    <h2 class="splash-subhead">
                        <p>Bem vindo, {% if user.is_authenticated %} {{user.username}}{% else %}Visitante{% endif %}!</p>
                    </h2>
                    <p>
                    <strong>Número de candidatos registrados:</strong> {{ count }}
                    </p>
                </div>
            </div>
        </div>
    </div>
        
  
   
{% endblock %}

core/templates/signup.html
  
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-8">
      <div class="card">
        <div class="card-body">
          <h2>Sign Up</h2>
          <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Sign up</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

vacancies/templates/vacancies/datails.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="splash">
    <div class="pure-g-r">
        <div class="pure-u-1">
            <div class="l-box splash-text">
                <h1 class="splash-head">
                    {{ vacancie }}
                </h1>
                <h2 class="splash-subhead">
                    {{ vacancie.description }}
                </h2>
                <p>
                    <a href="#" class="pure-button primary-button">Inscreva-se</a>
                </p>
            </div>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Sobre a Vaga</h4>
            {{ vacancie.about|linebreaks }}
        </div>
    </div>
    <div class="pure-u-1-3">
        
    </div>
</div>
{% endblock %}

vacancies/templates/vacancies/index.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <div class="container">
            <h4 class="content-subhead">Listagem de vagas do Site</h4>
            <p>Abaixo a lista de vagas disponíveis na plataforma:</p>
        </div>
    </div>
</div>
{% for vacancie in vacancies %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1-3">
        <div class="container">
            <a href="{{ vacancie.get_absolute_url }}">
            </a>
        </div>
    </div>
    <div class="pure-g-r content-ribbon">
        <div class="container">
            <h4 class="content-subhead"><a href="{{ vacancie.get_absolute_url }}" title="">{{ vacancie.name }}</a></h4>
            {{ vacancie.slug|linebreaks }}
           Faixa Salarial: {{ vacancie.salary|linebreaks }}
           Escolaridade Mínima: {{ vacancie.educational|linebreaks }}
        </div>
    </div>
</div>

{% endfor %}
{% endblock %}